// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihzaajimmaytorupdyvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloemFhamltbWF5dG9ydXBkeXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTQzODIsImV4cCI6MjA1Njk3MDM4Mn0.yLiSEqoYMqtpLn4HHkxkHhmXzPmA3AGyungZKXgKfTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);